### ISSUE TITLE
[Task] Category groups should sum up their child category stats

### ISSUE THREAD

**Issue by marvin-bitterlich** [BuildTeamDev/tokenbb-web-client#108]
TrackerID: #vn5x1
*(Use the TrackerID in branch names like `feature/implement-feature-xyz-#taskid`)*

## Overview

![image](https://user-images.githubusercontent.com/644950/58748649-4df19580-847c-11e9-9028-6ee5e40050c4.png)

Categories have statistics about their number of views and replies. Each Category Group should sum up their child categories and display the aggregated stats.

## Goals

- [ ] Recursively aggregate stats for groups
- [ ] Display these stats
- [ ] Adapt all themes to the new data

## Bounty

We are offering a 15 BT bounty for a merged pull request that solves this issue.

**Comment by tdreid** [comment]
On it! :+1:
