### ISSUE TITLE
[Task] Add VP and RC indicators for users

### ISSUE THREAD

**Issue by reggaemuffin** [BuildTeamDev/tokenbb-web-client#109]
TrackerID: #czrbw
*(Use the TrackerID in branch names like `feature/implement-feature-xyz-#taskid`)*

## Overview

A problem especially with new users is knowing how much voting power or resource credits one has. We should display them as energy bars, maybe next to the profile picker.

It could look similar to the tron wallet:
![image](https://user-images.githubusercontent.com/644950/58748758-4383cb80-847d-11e9-966b-731d6a93a710.png)

## Goals

- [ ] Retrieve VP and RC stats for linked user accounts
- [ ] Display these stats as energy bars
- [ ] Refetch data when the user did an action that affects RC and VP
- [ ] Refetch data periodically, say every minute
- [ ] Display a tooltip with some information as to what the numbers mean
- [ ] Adapt all themes to the new feature

## Bounty

We are offering a 50 BT bounty for a merged pull request that solves this issue.

**Comment by nojo121** [comment]
Working on it. 💪🏻
